### ISSUE TITLE
Remove Ivan

### ISSUE THREAD

**Issue by Kami-Interface** [Team-QUIET/QUIET-Community-Edition#115]

**Comment by PurpleMossClump** [comment]
Yeah, it's a weird idea to begin with. Drop-pod artillery? It's pretty out-there even for an Experimental design. If it could rapidly deploy a full squad of units, rather than dropping them one at a time, it would be somewhat useful, but as it is it's an annoyance at best. Better off just building Continentals if you want to get units somewhere at that stage in the game as UEF.

**Comment by Azraeel** [comment]
I was thinking about buffing this unit but this unit could quickly become the most oppressive and OP unit in the game as it has 40km of range and could build 2-3 pervicals and drop them anywhere across the entire map which is actually worst then Teleport RN, it's uncounterable Teleport.... 

So yes this is 100% getting removed.
