### ISSUE TITLE
[Short Term] Introduce Shield Regeneration Nerf

### ISSUE THREAD

**Issue by Azraeel** [Team-QUIET/QUIET-Community-Edition#172]

**Comment by PurpleMossClump** [comment]
This is something that should be done carefully. 
If the shields have too much downtime when depleted, they can feel useless to build since the generators themselves have extremely low HP; It can lead to situations where the shield is breached and the generator is killed long before it is even nearly back up. 
The inverse is also true, I recognize. If the shields are able to be nested, overlapping to cover one another, then they can seem unbreachable.

It's a fine space to balance. With the introduction of overspill, nesting shields should be less of an issue. A significant number of mobile artillery, rockets or dedicated anti-shield weapons should be able to make short work of them. 

If the issue is that nested mobile bubble shields are too effective, we might look at only nerfing the regen on those mobile shields.

**Comment by Azraeel** [comment]
Closed with PR #201
