### ISSUE TITLE
[Medium Term] Review T4 PD

### ISSUE THREAD

**Issue by Azraeel** [Team-QUIET/QUIET-Community-Edition#178]

**Comment by PurpleMossClump** [comment]
I'm assuming this issue has been posted to give our ongoing investigation into the Neolith and Mothra a place to document our findings? And, while we're at it, we'd may as well look into the other factions T4 PD for any problems that have gone unnoticed.

**Comment by PurpleMossClump** [comment]
After a quick bit of testing their DPS, here's what I've got for conclusions for the Seraphim and UEF T4 PDs. That is, the Excalibur and Blockhouse for UEF, and the Lambda Tower and Multirole Beam for the Seraphim.

All 4 are giving more or less the DPS listed in their tooltip. 
Specifically, a little less for the Excalibur, Blockhouse and Multirole Beam, while the Lambda Tower is doing a little more than the tooltip says. (In the case of the Lambda Tower, I find this acceptable given that it is the most expensive and has the shortest range of all the T4 PDs and also has the highest energy upkeep by far, costing 2500 E when idle and 10850 E when the weapon is charging)

**Comment by PurpleMossClump** [comment]
I've also tested each faction's T4 AA weapons.
The UEF has 2 dedicated T4 AA.
The Seraphim also has 2, with one being a Multirole weapon.

Starting with the AA guns
Cybran's T4 AA gun deals almost half the DPS listed on the tooltip.
The tooltip indicates 
8000 DMG, 4k DPS

While the game log shows about 2100~ DPS
info: , 262.20007324219, "vrb2302", "Sky Bloom", 8000, 2105, 2136, "No rounded DPS change"
info: , 266.00012207031, "vrb2302", "Sky Bloom", 8000, 2105, 2135
info: , 269.79992675781, "vrb2302", "Sky Bloom", 8000, 2105, 2135, "No rounded DPS change"

Checking the BP, I find
            Damage = 8000,
            EnergyDrainPerSecond = 1000,
            EnergyRequired = 2000,

            RateOfFire = 0.6,       -- 4000 DPS rate controlled by charge
So, according to the EnergyRequired/EnergyDrainPerSecond, the weapon should fire every 2 seconds, but the weapon is actually firing every 3.8~ seconds, according to the log. This checks out with the DPS, being 2100~ instead of 4000. 

All factions T4 AA guns perform identically, and have identical tooltips, log results and BP info. 
So, all 4 T4 AA guns are doing about half as much DPS as they should be, according to the tooltips.

The Seraphim T4 Multirole Beam PD performs as expected. It deals about 800~ DPS according to the log, which is close enough to the 850 listed by the tooltip. Not nearly as effective as any dedicated role PD, but decent for the cost. There's nothing wrong with this unit that I can identify without a deep dive.

The UEF T4 Mummy AA weapon is a curious case of 'it depends'. The weapon has a short range for a T4 dedicated AA weapon. It has 4 separate turrets which each have a locked firing arc that can overlap with the adjacent turrets, allowing them to engage separate targets or the same target if it crosses into their firing arcs. Each individual turret deals about the listed 1500 DPS listed on the tooltip, but the entire system itself is capable of dealing far more than that. But, again it depends on circumstances. (It might be a weapon that's been slept on. I'll try building it in practical situations to see how it performs)
