### ISSUE TITLE
Small Mongoose range nerf

### ISSUE THREAD

**Issue by rajderks** [Team-QUIET/QUIET-Community-Edition#191]
The Mongoose has been a really powerful tool in m28's arsenal for quite some games now, straight up winning him games without having any viable counter in my opinion. Its the only thing hes building, completely foregoing any other t2 unit besides shields and tml.
I would like to propose a reduction of a 2-4 range nerf.  (current value is 34)

replay for "proof": https://discord.com/channels/1280278037434204203/1280287252379074570/1289220369001091164

**Comment by rajderks** [comment]
@Azraeel what do you think of this?

**Comment by rajderks** [comment]
Here are some ranges in the T2 spectrum for reference

mongoose: 34
zealot: 24
rommel: 32 (t2.5 unit)
amphorak: 34 (t2.5 unit)
pillar: 24
rhino: 27
hoplite: 42 (really?)
predator: 42 (sniper)
hippo: 25/32 (rockets)
il;shavoh: 28
Onyzum: 25
Yenzyne: 25

the hoplite is an outlier i guess, but the tendense is around 26 average for the other t2 units. Especially seraphim has a hard time hitting them.

**Comment by PurpleMossClump** [comment]
The Hoplite has about 2/3 the DPS of the Mongoose, less HP
I think the Mongoose stands out so much because it's doing almost 80 DPS with all that range. Yeah, I agree it should probably have a range nerf. In fact, it used to be only the grenade launcher had so much range; The gatling cannon range was much shorter. I don't know when the gatling cannon range got bumped up to match the grenade launcher, but that was a huge buff.

**Comment by Azraeel** [comment]
Fixed in PR 193 (194) i forget
