### ISSUE TITLE
[Medium Term] Rework MMLs

### ISSUE THREAD

**Issue by Azraeel** [Team-QUIET/QUIET-Community-Edition#239]

**Comment by Azraeel** [comment]
https://github.com/Team-QUIET/QUIET-Community-Edition/issues/233

Refer Here.

**Comment by AmericanSniper** [comment]
Just would be nice to make other MML spam viable for other factions, I'm fine in keeping Cybran variant strongest, but I'd like to have the difference not that obvious, such as in FAF, also FAF MMLs have smaller range, which I'm fine because FAF doesn't have units like Dalek, or Tower Boss. But it's obvious too me and other players that they're too spamable, desperately in compare with T1 Mob Artillery. I prefer just taking FAF's Stats of this unit, but keeping speed of 2.2, and increased range to 70.

**Comment by PurpleMossClump** [comment]
I got a few ideas for this.

- 10 second reload is standard
- Movement speed reduced
- Cybran: No other changes. Missile splits into multiple projectiles, so that's its strength.
- Aeon: Slightly more range than other factions.
- Seraphim: Missile is a little faster than other factions.
- UEF: 8 second reload; Needs fewer launchers to achieve the same volume of fire.
